[2022-11-22T12:29:18.098+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_postgres_operator_v1.create_postgres_table manual__2022-11-22T12:20:26.951020+00:00 [queued]>
[2022-11-22T12:29:18.123+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_postgres_operator_v1.create_postgres_table manual__2022-11-22T12:20:26.951020+00:00 [queued]>
[2022-11-22T12:29:18.124+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-22T12:29:18.124+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 6
[2022-11-22T12:29:18.125+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-22T12:29:18.167+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2022-11-22 12:20:26.951020+00:00
[2022-11-22T12:29:18.177+0000] {standard_task_runner.py:55} INFO - Started process 1662 to run task
[2022-11-22T12:29:18.183+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_postgres_operator_v1', 'create_postgres_table', 'manual__2022-11-22T12:20:26.951020+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dag_postgres.py', '--cfg-path', '/tmp/tmpwpez7rmg']
[2022-11-22T12:29:18.186+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask create_postgres_table
[2022-11-22T12:29:18.374+0000] {task_command.py:376} INFO - Running <TaskInstance: dag_postgres_operator_v1.create_postgres_table manual__2022-11-22T12:20:26.951020+00:00 [running]> on host 51961a9d5f51
[2022-11-22T12:29:18.580+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=JG13
AIRFLOW_CTX_DAG_ID=dag_postgres_operator_v1
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-22T12:20:26.951020+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-22T12:20:26.951020+00:00
[2022-11-22T12:29:18.639+0000] {base.py:71} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-11-22T12:29:18.646+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 288, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 115, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

[2022-11-22T12:29:18.668+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_postgres_operator_v1, task_id=create_postgres_table, execution_date=20221122T122026, start_date=20221122T122918, end_date=20221122T122918
[2022-11-22T12:29:18.692+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 4 for task create_postgres_table (connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
; 1662)
[2022-11-22T12:29:18.738+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-22T12:29:18.782+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
