[2022-11-22T12:49:33.402+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_postgres_operator_v1.create_postgres_table manual__2022-11-22T12:29:25.132527+00:00 [queued]>
[2022-11-22T12:49:33.415+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_postgres_operator_v1.create_postgres_table manual__2022-11-22T12:29:25.132527+00:00 [queued]>
[2022-11-22T12:49:33.416+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-22T12:49:33.416+0000] {taskinstance.py:1363} INFO - Starting attempt 5 of 6
[2022-11-22T12:49:33.416+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-22T12:49:33.437+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2022-11-22 12:29:25.132527+00:00
[2022-11-22T12:49:33.443+0000] {standard_task_runner.py:55} INFO - Started process 3764 to run task
[2022-11-22T12:49:33.446+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_postgres_operator_v1', 'create_postgres_table', 'manual__2022-11-22T12:29:25.132527+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dag_postgres.py', '--cfg-path', '/tmp/tmpt2pbo7uu']
[2022-11-22T12:49:33.449+0000] {standard_task_runner.py:83} INFO - Job 13: Subtask create_postgres_table
[2022-11-22T12:49:33.541+0000] {task_command.py:376} INFO - Running <TaskInstance: dag_postgres_operator_v1.create_postgres_table manual__2022-11-22T12:29:25.132527+00:00 [running]> on host 51961a9d5f51
[2022-11-22T12:49:33.649+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=JG13
AIRFLOW_CTX_DAG_ID=dag_postgres_operator_v1
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-22T12:29:25.132527+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-22T12:29:25.132527+00:00
[2022-11-22T12:49:33.659+0000] {base.py:71} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-11-22T12:49:33.660+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 288, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 115, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

[2022-11-22T12:49:33.670+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_postgres_operator_v1, task_id=create_postgres_table, execution_date=20221122T122925, start_date=20221122T124933, end_date=20221122T124933
[2022-11-22T12:49:33.685+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 13 for task create_postgres_table (connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
; 3764)
[2022-11-22T12:49:33.699+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-22T12:49:33.721+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
